<div class="container-indent nomargin">
    <div class="container-fluid">
        <div class="row">
            <div class="slider-revolution revolution-default" data-fullscreen="false">
                <div class="tp-banner-container" style="overflow: visible;">
                    <div class="tp-banner revolution revslider-initialised tp-simpleresponsive" id="revslider-497" style="height: 800px;">
                        <ul style="display: block; overflow: hidden; width: 100%; height: 100%; max-height: none;" class="tp-revslider-mainul">
                            <li data-thumb="//santaichinh24h.vn/files/images/slider-image/slider1.png" data-transition="fade" data-slotamount="1" data-masterspeed="1000" data-saveperformance="off" data-title="Slide" class="tp-revslider-slidesli active-revslide" style="width: 100%; height: 100%; overflow: hidden; z-index: 18; visibility: hidden; opacity: 0;">
                                <div class="slotholder" style="width:100%;height:100%;" data-duration="undefined" data-zoomstart="undefined" data-zoomend="undefined" data-rotationstart="undefined" data-rotationend="undefined" data-ease="undefined" data-bgpositionend="undefined" data-bgposition="center center" data-kenburns="undefined" data-easeme="undefined" data-bgfit="cover" data-bgfitend="undefined" data-owidth="undefined" data-oheight="undefined">
                                    <div class="tp-bgimg defaultimg" data-lazyload="undefined" data-bgfit="cover" data-bgposition="center center" data-bgrepeat="no-repeat" data-lazydone="undefined" src="//santaichinh24h.vn/files/images/slider-image/slider1.png" data-src="//santaichinh24h.vn/files/images/slider-image/slider1.png" style="background-color: rgba(0, 0, 0, 0); background-repeat: no-repeat; background-image: url(&quot;//santaichinh24h.vn/files/images/slider-image/slider1.png&quot;); background-size: cover; background-position: center center; width: 100%; height: 100%; opacity: 1; visibility: inherit;"></div>
                                    <div class="tp-dottedoverlay true"></div>
                                </div>
                                <div class="tp-caption tp-caption1 text-left lfl stb start" data-x="left" data-y="center" data-hoffset="281" data-voffset="-20" data-speed="600" data-start="900" data-easing="Power4.easeOut" data-endeasing="Power4.easeIn" style="transition: all 0s ease 0s; min-height: 0px; min-width: 0px; line-height: 22px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 0px; font-size: 14px; left: 378px; top: 380px; visibility: visible; opacity: 0; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, -0.0025, 0, 50, 0, 1);"></div>
                            </li>
                            <li data-thumb="//santaichinh24h.vn/files/images/slider-image/slider2.png" data-transition="fade" data-slotamount="1" data-masterspeed="1000" data-saveperformance="off" data-title="Slide" class="tp-revslider-slidesli active-revslide current-sr-slide-visible" style="width: 100%; height: 100%; overflow: hidden; z-index: 20; visibility: inherit; opacity: 1;">
                                <div class="slotholder" style="width:100%;height:100%;" data-duration="undefined" data-zoomstart="undefined" data-zoomend="undefined" data-rotationstart="undefined" data-rotationend="undefined" data-ease="undefined" data-bgpositionend="undefined" data-bgposition="center center" data-kenburns="undefined" data-easeme="undefined" data-bgfit="cover" data-bgfitend="undefined" data-owidth="undefined" data-oheight="undefined">
                                    <div class="tp-bgimg defaultimg" data-lazyload="undefined" data-bgfit="cover" data-bgposition="center center" data-bgrepeat="no-repeat" data-lazydone="undefined" src="//santaichinh24h.vn/files/images/slider-image/slider2.png" data-src="//santaichinh24h.vn/files/images/slider-image/slider2.png" style="background-color: rgba(0, 0, 0, 0); background-repeat: no-repeat; background-image: url(&quot;//santaichinh24h.vn/files/images/slider-image/slider2.png&quot;); background-size: cover; background-position: center center; width: 100%; height: 100%; opacity: 1; visibility: inherit;"></div>
                                    <div class="tp-dottedoverlay true"></div>
                                </div>
                                <div class="tp-caption tp-caption1 text-left lfl stb start" data-x="left" data-y="center" data-hoffset="281" data-voffset="-20" data-speed="600" data-start="900" data-easing="Power4.easeOut" data-endeasing="Power4.easeIn" style="transition: all 0s ease 0s; min-height: 0px; min-width: 0px; line-height: 22px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 0px; font-size: 14px; left: 378px; top: 380px; visibility: visible; opacity: 1; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, -0.0025, 0, 0, 0, 1);"></div>
                            </li>
                            <li data-thumb="//santaichinh24h.vn/files/images/slider-image/slider3.png" data-transition="fade" data-slotamount="1" data-masterspeed="1000" data-saveperformance="off" data-title="Slide" class="tp-revslider-slidesli active-revslide" style="width: 100%; height: 100%; overflow: hidden; visibility: hidden; opacity: 0; z-index: 18;">
                                <div class="slotholder" style="width:100%;height:100%;" data-duration="undefined" data-zoomstart="undefined" data-zoomend="undefined" data-rotationstart="undefined" data-rotationend="undefined" data-ease="undefined" data-bgpositionend="undefined" data-bgposition="center center" data-kenburns="undefined" data-easeme="undefined" data-bgfit="cover" data-bgfitend="undefined" data-owidth="undefined" data-oheight="undefined">
                                    <div class="tp-bgimg defaultimg" data-lazyload="undefined" data-bgfit="cover" data-bgposition="center center" data-bgrepeat="no-repeat" data-lazydone="undefined" src="//santaichinh24h.vn/files/images/slider-image/slider3.png" data-src="//santaichinh24h.vn/files/images/slider-image/slider3.png" style="background-color: rgba(0, 0, 0, 0); background-repeat: no-repeat; background-image: url(&quot;//santaichinh24h.vn/files/images/slider-image/slider3.png&quot;); background-size: cover; background-position: center center; width: 100%; height: 100%; opacity: 1; visibility: inherit;"></div>
                                    <div class="tp-dottedoverlay true"></div>
                                </div>
                                <div class="tp-caption tp-caption1 text-left lfl stb start" data-x="left" data-y="center" data-hoffset="281" data-voffset="-20" data-speed="600" data-start="900" data-easing="Power4.easeOut" data-endeasing="Power4.easeIn" style="transition: all 0s ease 0s; min-height: 0px; min-width: 0px; line-height: 22px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 0px; font-size: 14px; left: 378px; top: 380px; visibility: visible; opacity: 0; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, -0.0025, 0, 50, 0, 1);"></div>
                            </li>
                        </ul>
                        <div class="tp-bannertimer" style="visibility: hidden; width: 68%; transform: translate3d(0px, 0px, 0px);"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>